#ifndef CODE_GUIMAI_VOICE_CONFIG_LOCAL_H_
#define CODE_GUIMAI_VOICE_CONFIG_LOCAL_H_

#define GUIMAI_FW_TAG                  "21kd-8.26-adc-audio"

#define GUIMAI_WIFI_SSID               "LTL"
#define GUIMAI_WIFI_PASSWORD           "3170851279"
#define GUIMAI_WIFI_TARGET_IP          "192.168.193.163"
#define GUIMAI_WIFI_TARGET_PORT        "8080"
#define GUIMAI_WIFI_INIT_RETRY         (1)
#define GUIMAI_WIFI_INIT_ON_BOOT       (1)
#define GUIMAI_WIFI_INIT_ON_RECORD     (0)
#define GUIMAI_WIFI_USE_RTS_FLOW       (0)

#define GUIMAI_MUSIC_ENABLE            (0)
#define GUIMAI_HORN_BLOCKING_PLAY      (1)
#define GUIMAI_HORN_USE_BUZZER         (1)
#define GUIMAI_HORN_PWM_TEST_ALWAYS_ON (0)
#define GUIMAI_HORN_PWM_TEST_FREQ_HZ   (1000U)
#define GUIMAI_HORN_PWM_TEST_DUTY      (5000U)
#define GUIMAI_HORN_PWM_DUTY           (5000U)
#define GUIMAI_VOICE_EXTERNAL_TRIGGER  (1)
#define GUIMAI_TRIGGER_USE_XL9555_KEY3 (0)
#define GUIMAI_VOICE_INIT_LORA         (0)
#define GUIMAI_VOICE_LIGHT_HORN_GAP_MS (600U)

#define GUIMAI_RECORD_DEFER_TX         (1)
#define GUIMAI_RECORD_TIGHT_LOOP       (1)
#define GUIMAI_RECORD_USE_CPU1         (0)
#define GUIMAI_RECORD_USE_CPU2         (1)
#define GUIMAI_RECORD_STREAM_TX        (1)
#define GUIMAI_STREAM_TX_QUEUE_DEPTH   (16U)
#define GUIMAI_STREAM_TX_DEBUG         (1)
#define GUIMAI_STREAM_TX_DIRECT_UART   (1)
#define GUIMAI_STREAM_TX_UNCACHED_ALIAS (1)
#define GUIMAI_LINEIN_IIS_FORMAT       GUIMAI_IIS_FMT_I2S
#define GUIMAI_LINEIN_AUTO_PROBE       (0)
#define GUIMAI_LINEIN_INIT_ON_BOOT     (1)
#define GUIMAI_GTM_DMA_CAPTURE         (0)
#define GUIMAI_GTM_DMA_SAMPLE_LEADING_EDGE (0)
#define GUIMAI_GTM_DMA_LEFT_WS_LEVEL   (1U)
#define GUIMAI_GTM_DMA_I2S_DELAY_BITS  (0U)
#define GUIMAI_RECORD_CLOCK_RETRY_ENABLE (0)
#define GUIMAI_RECORD_CLOCK_PUMP_ENABLE (0)
#define GUIMAI_RECORD_CLOCK_PUMP_MAX_FRAMES (64U)
#define GUIMAI_LINEIN_READ_BATCH       (256U)
#define GUIMAI_RECORD_PCM_TRANSFORM_MODE (0U)
#define GUIMAI_AUDIO_HOTPATH_LOG       (1)
#define GUIMAI_AUDIO_RUNTIME_DIAG      (0)

#define GUIMAI_GTM_TBCM_DIAG           (0)
#define GUIMAI_GTM_TIM_TSSM_DIAG       (0)
#define GUIMAI_GTM_TIM_TSSM_TDU_DIAG   (0)
#define GUIMAI_GTM_ARU_FIFO_DIAG       (0)
#define GUIMAI_GTM_AFD_DMA_DIAG        (0)
#define GUIMAI_GTM_TBCM_DECODE_DIAG    (0)

#endif /* CODE_GUIMAI_VOICE_CONFIG_LOCAL_H_ */
